version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto25
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn clean install
    - mkdir -p lib
    - mv pay-stubs-main-app/target/pay-stubs-main-app-1.0.jar lib/
artifacts:
  files:
  - "lib/**/*"